// Trace recorder — persists subagent lifecycle events to JSONL files on disk.
//
// Subscribes to the events emitted by `src/shared/subagent-events.ts` via
// `pi.events.on(...)` and appends each event as a single JSON line to:
//
//   .pi/traces/subagents/{traceRunId}.jsonl   (one file per trace)
//
// The trace files can then be consumed by:
// - The morning report cron (cost/usage summary)
// - The harness evolver (pattern analysis)
// - pi-agent-observability (live dashboard integration)
// - Manual analysis (read with `jq` or `cat`)
//
// Each JSONL line has the shape:
//   { "ts": "2026-06-09T...", "type": "subagent.run_start", "payload": {...} }

import * as fs from "node:fs";
import * as path from "node:path";
import { randomUUID } from "node:crypto";
import {
	SUBAGENT_BUDGET_EXHAUSTED_EVENT,
	SUBAGENT_COST_CHECKPOINT_EVENT,
	SUBAGENT_MANIFEST_WRITTEN_EVENT,
	SUBAGENT_RUN_END_EVENT,
	SUBAGENT_RUN_RETRY_EVENT,
	SUBAGENT_RUN_START_EVENT,
	SUBAGENT_TIMEOUT_EVENT,
} from "./subagent-events.ts";

const TRACE_DIR = ".pi/traces/subagents";
const RETENTION_DAYS = 14;
const ALL_EVENTS = [
	SUBAGENT_RUN_START_EVENT,
	SUBAGENT_RUN_END_EVENT,
	SUBAGENT_RUN_RETRY_EVENT,
	SUBAGENT_COST_CHECKPOINT_EVENT,
	SUBAGENT_BUDGET_EXHAUSTED_EVENT,
	SUBAGENT_TIMEOUT_EVENT,
	SUBAGENT_MANIFEST_WRITTEN_EVENT,
] as const;

/** JSONL line shape. */
interface TraceLine {
	ts: string;
	type: string;
	payload: unknown;
}

/**
 * TraceRecorder — listens to subagent events and writes them to a JSONL file.
 *
 * Usage:
 *   const recorder = new TraceRecorder(pi);
 *   recorder.install();           // subscribe to events
 *   // ... later
 *   recorder.flush();             // ensure all writes hit disk
 *   recorder.uninstall();         // unsubscribe (e.g. on extension reload)
 */
export class TraceRecorder {
	private readonly pi: { events: { on: (event: string, handler: (payload: unknown) => void) => void; off?: (event: string, handler: (payload: unknown) => void) => void } };
	private readonly traceDir: string;
	private readonly writeQueue: Map<string, Promise<void>> = new Map();
	private readonly handlers: Map<string, (payload: unknown) => void> = new Map();
	private installed = false;

	constructor(pi: TraceRecorder["pi"], traceDir: string = TRACE_DIR) {
		this.pi = pi;
		this.traceDir = traceDir;
	}

	/** Subscribe to all subagent events. Idempotent. */
	install(): void {
		if (this.installed) return;
		this.installed = true;

		// Ensure trace directory exists
		try {
			fs.mkdirSync(this.traceDir, { recursive: true });
		} catch {
			// Non-fatal: traces are best-effort. The recorder will retry
			// on each write.
		}

		for (const eventName of ALL_EVENTS) {
			const handler = (payload: unknown) => this.handleEvent(eventName, payload);
			this.handlers.set(eventName, handler);
			this.pi.events.on(eventName, handler);
		}
	}

	/** Unsubscribe from all events. Safe to call multiple times. */
	uninstall(): void {
		if (!this.installed) return;
		this.installed = false;
		for (const [eventName, handler] of this.handlers) {
			if (this.pi.events.off) this.pi.events.off(eventName, handler);
		}
		this.handlers.clear();
	}

	/** Wait for all pending writes to complete. */
	async flush(): Promise<void> {
		await Promise.all(this.writeQueue.values());
	}

	/**
	 * Delete trace files older than RETENTION_DAYS. Best-effort.
	 * Returns the number of files deleted.
	 */
	cleanup(retentionDays: number = RETENTION_DAYS): number {
		const cutoff = Date.now() - retentionDays * 24 * 60 * 60 * 1000;
		let deleted = 0;
		try {
			const files = fs.readdirSync(this.traceDir);
			for (const file of files) {
				if (!file.endsWith(".jsonl")) continue;
				const filePath = path.join(this.traceDir, file);
				const stat = fs.lstatSync(filePath);
				if (stat.isFile() && stat.mtimeMs < cutoff) {
					fs.unlinkSync(filePath);
					deleted++;
				}
			}
		} catch {
			// Non-fatal
		}
		return deleted;
	}

	/** Test/diagnostic: read the trace file for a given runId. */
	read(runId: string): TraceLine[] {
		const filePath = this.pathFor(runId);
		try {
			const content = fs.readFileSync(filePath, "utf-8");
			return content
				.split("\n")
				.filter((line) => line.trim())
				.map((line) => JSON.parse(line) as TraceLine);
		} catch {
			return [];
		}
	}

	/** Test/diagnostic: list all run IDs that have trace files. */
	listRuns(): string[] {
		try {
			return fs.readdirSync(this.traceDir)
				.filter((f) => f.endsWith(".jsonl"))
				.map((f) => f.replace(/\.jsonl$/, ""));
		} catch {
			return [];
		}
	}

	private pathFor(runId: string): string {
		// Sanitize the runId to prevent path traversal. The trace ID is
		// generated by us (randomUUID) so it should be safe, but defensively
		// strip any non-alphanumeric/dash/underscore chars.
		const safe = runId.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64);
		return path.join(this.traceDir, `${safe}.jsonl`);
	}

	private handleEvent(eventName: string, payload: unknown): void {
		// This is the bus-receive role. Called by `pi.events.on(...)` handlers
		// we registered in install(). We write to file but DO NOT re-emit on
		// the bus — that would create infinite recursion (emit → handler →
		// emit → handler → ...).
		// Determine the trace file for this event. Priority:
		// 1. payload.traceRunId (if present)
		// 2. payload.runId (fallback)
		const p = (payload ?? {}) as { traceRunId?: string; runId?: string };
		const traceId = p.traceRunId ?? p.runId ?? randomUUID();

		const line: TraceLine = {
			ts: new Date().toISOString(),
			type: eventName,
			payload,
		};

		// Serialize write per file to avoid interleaving. Chain promises so
		// writes happen in order, but different traces don't block each other.
		const prev = this.writeQueue.get(traceId) ?? Promise.resolve();
		const next = prev
			.then(() => this.writeLine(this.pathFor(traceId), line))
			.catch((err) => {
				// Non-fatal: log and continue
				console.error(`[trace-recorder] failed to write ${eventName}:`, err);
			})
			.finally(() => {
				// Clean up queue entry if no new writes pending
				if (this.writeQueue.get(traceId) === next) {
					this.writeQueue.delete(traceId);
				}
			});
		this.writeQueue.set(traceId, next);
	}

	/**
	 * Public emit — use this from cron jobs, the extension, or any other
	 * producer that wants to surface an event AND have it persisted.
	 *
	 * This is the only path that calls `pi.events.emit` — it does NOT go
	 * through `handleEvent` (that would be the bus-receive path and would
	 * create infinite recursion).
	 *
	 * Other consumers (like the file writer via `install()`) will receive
	 * the event through their normal `pi.events.on(...)` subscriptions.
	 */
	emit(eventName: string, payload: unknown): void {
		const bus = (this.pi as { events?: { emit?: (e: string, p: unknown) => void } }).events;
		if (!bus?.emit) return; // No bus to emit on (test isolation or minimal fake)
		try { bus.emit(eventName, payload); } catch { /* non-fatal */ }
	}

	private async writeLine(filePath: string, line: TraceLine): Promise<void> {
		// Ensure parent directory exists (in case it was deleted between
		// install() and now).
		fs.mkdirSync(path.dirname(filePath), { recursive: true });
		await fs.promises.appendFile(filePath, JSON.stringify(line) + "\n", "utf-8");
	}
}
